### PR TITLE
Fix: Email regex to allow consecutive special chars

### LINKED ISSUE #248: [PE-D][Tester D] Email format not specific (2 special characters beside)
Steps to reproduce:
edit 1 e/ee_.ss@cc.com

The User Guide and error message does not state any constraints that within the local-part of the email, there cannot be two special characters (+\_.-) beside each other as shown in my test input. The email "ee\_.ss@cc.com" should have been valid but instead is not accepted.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: danplatypus30/ped#3

### PR DESCRIPTION
**Pull request by twhjames**
**LoC Changed: 17 Line**

Fixes #248 

Updated email validation regex to allow consecutive special characters in the local part, as highlighted in the issue. Also refined the domain regex to ensure valid top-level domain (TLD) handling.

### CODE REVIEW

File: src/main/java/seedu/recruittrackpro/model/person/Email.java [hunk 1]
```diff
@@ -21,14 +21,16 @@ public class Email {
...
-    private static final String ALPHANUMERIC_NO_UNDERSCORE = "[^\\W_]+"; // alphanumeric characters except underscore
-    private static final String LOCAL_PART_REGEX = "^" + ALPHANUMERIC_NO_UNDERSCORE + "([" + SPECIAL_CHARACTERS + "]"
-            + ALPHANUMERIC_NO_UNDERSCORE + ")*";
-    private static final String DOMAIN_PART_REGEX = ALPHANUMERIC_NO_UNDERSCORE
-            + "(-" + ALPHANUMERIC_NO_UNDERSCORE + ")*";
-    private static final String DOMAIN_LAST_PART_REGEX = "(" + DOMAIN_PART_REGEX + "){2,}$"; // At least two chars
-    private static final String DOMAIN_REGEX = "(" + DOMAIN_PART_REGEX + "\\.)*" + DOMAIN_LAST_PART_REGEX;
+
+    // Local-part: starts and ends with alphanum, allows special characters in between
+    private static final String LOCAL_PART_REGEX = "^[a-zA-Z0-9](?:[a-zA-Z0-9+_.-]*[a-zA-Z0-9])?";
```
Comment (delonlee01) [inline src/main/java/seedu/recruittrackpro/model/person/Email.java:26]: Reading [this](https://snov.io/knowledgebase/what-is-a-valid-email-address-format/#:~:text=there%20are%20specific-,requirements,-for%20acceptable%20usernames), I realised that the tester was not saying that consecutive special characters is a valid email (cause it is not).

Instead, he is trying to say that the UG and error messages did not say it is invalid. So he _assumed_ that it is allowed, which prompted the bug report.

For #248, could we revert the change for `LOCAL_PART_REGEX` and update the UG/error message accordingly?

Comment (twhjames) [reply src/main/java/seedu/recruittrackpro/model/person/Email.java]: Understood. I have referred to the blog for both local and domain validation, and updated the command usage and UG accordingly:
image

Note that the double <br> was needed, else it will look like this:
image

File: docs/UserGuide.md [hunk 2]
```diff
@@ -75,6 +75,13 @@ management tasks done faster than traditional GUI apps.
 * Extraneous parameters for commands that do not take in parameters (such as `help`, `list`, `exit` and `clear`) will be ignored.<br>
   e.g. if the command specifies `help 123`, it will be interpreted as `help`.
 
+* For `e/EMAIL`, the email must follow a valid format: `local-part@domain`.
+  - The local-part may include alphanumeric characters and special characters (`.`, `_`, `-`)
+  - It must **not** start or end with a special character 
+  - It must **not** contain **consecutive special characters** (e.g., `john..doe@example.com` is invalid)
```
Comment (delonlee01) [inline docs/UserGuide.md:81]: Would indenting one more level be better?

I am wondering if people would intentionally interpret it differently. The "It" here could be referring to "the email" in line 78.

Comment (twhjames) [reply docs/UserGuide.md]: I have formatted the content as such:
image

It seems there’s a styling issue in MarkBind when using nested lists inside a `<box>`, and adding double `<br>` tags causes uneven spacing.

**Review by delonlee01 — APPROVED** [review]

File: src/main/java/seedu/recruittrackpro/model/person/Email.java [hunk 3]
```diff
@@ -13,22 +13,23 @@ public class Email {
...
             + "1. The local-part should only contain alphanumeric characters and these special characters, excluding "
-            + "the parentheses, (" + SPECIAL_CHARACTERS + "). The local-part may not start or end with any special "
-            + "characters.\n"
+            + "the parentheses, (" + SPECIAL_CHARACTERS + ").\n"
+            + "   - The local-part may not start or end with any special characters.\n"
+            + "   - Consecutive special characters are not allowed.\n"
             + "2. This is followed by a '@' and then a domain name. The domain name is made up of domain labels "
             + "separated by periods.\n"
             + "The domain name must:\n"
             + "    - end with a domain label at least 2 characters long\n"
```
Comment (delonlee01) [inline src/main/java/seedu/recruittrackpro/model/person/Email.java:22]: Sorry, realised there's one more change here.

With the inclusion of TLD, this statement needs to be updated.

**Review by delonlee01 — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/recruittrackpro/model/person/Email.java (hunk 3 above)
Comment (twhjames) [reply src/main/java/seedu/recruittrackpro/model/person/Email.java]: Great catch, I have updated both command usage and UG for this.

**Review by delonlee01 — APPROVED** [review]
